sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: Jr9EMo26/dXMKuu+1JFmY63c1EMizWUEctPP2/td+OEVLvCJ3bsw5NHVdEv735orSvZ6Q2hKqj8FOA9QFZ5xW4KsZabOAk22UUh0/mmx2xsXQWVXLK+TFLRoHPvgdfTDVjJmGRzxrwr+5wOqGRLccsr+ttBV6tOF3nZ5xUcvvetj+RF9je6/JM4va60SE2xdyfgJt1hGl+NytFCtfjAGcNVg3DQJFBbfL8Z31UCfXqfpvxNJ1dah7J253635gH/R5f35Hy/OAfG6joXP0yymc7ubAqAp0H7mzIH/WltVaKNDFo6LDoYfHj3+/pY0stbpTsTbaO0zPlDo7189descAdjuyaV0ys5pC33JEg0RRZK/HwC7RlyDhd0GXoPS15l8v2ljKfbfSrm2Cg7fFwau9T+UhuXuYrnSwnIQ34CbxYNwAgh+KGbruoOw4A0nZFdNZcGE0RcmKDOwP/pIf+aV9JSeXFUy72MexdGLhP+o51QEvIXqRW88ki2WYkIcvMg0p2FzlD7iHvsdfhEMqnWgARK42CE8Ie22KcZsbPqse5lehblB5odHhIiJdA2IMx+lef9CSbmKMfX4eBxrmZ6M/iLzh3UqhW1wf+N2JXKkKoxr+QpoztVnYAmqBpeZ6noI+SmbM5Qu6yc+7bhb/wCyk1fM5IvxyeWBM5uCO8EkVpc=
branches: 
only:
- master
