sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: ABPRmzIjNo4tDqFz+5rldPqJAKoWUMFhAZ7AVmmNEtEYJgD+D+yjh/4nIjYHEEEuHQA23mf272kYIy1n4aMQack3ucKoSobWnL0TXDPVoO/cMgP13tXSND3/8CmA4oinBaE9lo9zOI4W2yswtA0dRsAQgTuAeS7lPsrAJ3Gv0HqBMCVr2AXq6ze+jVzVnU66wJpl2XBrHRvktU/y9aH7MiqG3WXCtnyThkhN1vSP3HW/ygDxmajMvS3c1esCrvBo6ab8aMsXR2oJ+crjPt1PIN+DoEMtXGp0GpRxkEA2qbafDjE+SAJ10exjHnv19I1mJq4t81o6tMhaPOBe4LdK+E0wgr7GtvCu99W58viOJaMW2bSfE8TlbdKM8wR9qQr0q3rRpoSp7i5kC7QbgAfPiPwp3assm2zGhzGd6EtC2Wo9FB36qwXMcu+u3ee5AyxpBDyD6mszZQdK0deLSbVc4TtGoix8LNu9A3g66cvPrsHUj9gtkY4y/RR+yUDTwvTiuqpoMOzht/IB+9OKed1eL7l2ifUX/NGO2jx42ItD1iDmXAkFaCb6UJ/nkZCXdnL51PCWJKPWae+8vYTgbidCa0p9p8u5j894D8f3jIMSLTkS8bn+EKC3vA9Y5W7J6Yo83DuDSzrPzN1VDFvSAng+PwzFtM/t5TOd5rYL//xKqAM=
branches: 
only:
- master
