sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: QmLht1phS2xxIRXKwzGcMGmFVIXsASvEOBb9Wxgq7FjcnQh0/X2wEfkw4okM5PHwnhUGOlB3sIcyOXS0FRJvCAFplShT6e5l+Orfr5J+xBKw8qXust+R0QRwX8rUBnvdNmHyh/KkAzRmegF5i4kpDEMZe51qEoSm8hmFIguhEL93YkvwnKhX042uX4T0XkldjbDkXcJ/SEXUDNkpzmcHjnw63HBOeYAZrMRCrI+wGlVpHKVtHJD2ylTm2BENsq+nSs6lyKlq1Nnb9o4f5m4pKfT599jT0hExODoQNYzP4JER4X2N4QwM5k4IoaHDxTf9N3kcAXhsGczsPEYjUMeL0UrJjRPY8vmwGn2dpiUXcrIJbPW6B+semOjAapmzTj1lroX/GsDqT/tMQ3CTU/YQa2lPlRWuWFFFyN+WPNw2xXOcemdPFxnD5Kh19+Rfvw3oGD/da1bHVt8fbExGrvXvXePMbn1UoMgDdH8SsvuEutQb7eDf62OGLKCJmJwthkRzx7EMNe/3Aks4kY7OAQR3bQzOFJvGqUZRjiXiugOa135J7riPT2+tsvq2qgRNY7h1nXfOS/c/Gqv7N+utMQKcG71XDxrcxwU3obmISRMIn/gD5lAHFfHFY1U+gFpkQCSPzKv9Y6WaWW456jB2A2DyrW4SVeh8EzsPiO1vMqSjfUo=
branches: 
only:
- master
