sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: E4vNcdYXgShD+5ngvK+EiaQnVU7b5knOpEMW/c3ONqaDYTiaZluwTgdMs5edBMShsiXzCYjm6R0IqdQn91WvFdJRfgulzDP1GYRUuopKG1255lR30TnZ3kR3FgODCwAQT907B9i6248RhKEL5A6K/Iram0hQUWkc8zewHLmvEXR9tk0fNMoxE3Us+fU+oqhG7a3HXeeAB78OrkCy57mnaBhXoxbNqvMgIGyMI4ad/LHTshAcAiJCchv3/xW99WmIue+4IcmuqhGJ6lPxlaFGxWEOcjXwcRhJqBzKiDY5/jMZFTFCScrLWEvGW93gfbww2HDiF+WhP19QBRswcgsh0LkE57vrX4O4sq1Z2U3VwD4g+vYI0SW6elC6UuV3ZdT9hS9RFi09TboUdyXf8yKWAXTShB0JjtA1fipa/4C0PUV8mZ1b6kpPGoSnQg9VREB9mZfZdc/mYxrwPZbFjWq1F5uGajigbAskOrslWf+QTyHlZ3tZWGdEwi9+W7waMyUG1fgJtChAWh5em1WCCeFtP/2z5n5upQou5BhfL89MQ421Ox34PQR05jGkjdUFDXlOMp7BJ/7HYDzyAD5LeMnjLoqupCcwohKpYCcvpnYqD4k4O58DQbcHNBTy0L9iEltnT8+j/Fs/zD6f/moziQ0ALndcZM8KrmGe3VgaOhCrHzE=
branches: 
only:
- master
