sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "ThSx+oL+bs1M+QEbRi5OKI4QXZ1iwwVBTyFg3yp30TdQBBIHWrzfpJgS1ENKb57InVwnILSw5ikZfJrOgdyRjKfpnt8BOwtbcVgbqbxLEM/6a3LVzODgWYqWrAfu70syCcZG4r/395f5LcBZNkreQgjVa/jK1A3dzpFK4g1r3snF2SLciyc2wCCa7ybMnzGyGvNIb0JScdtSiZzsSsqGXgJ48ch2Ud3nYc9DxkSg2mMwV5Gk9H94zSY0vcSQIbavd7JXrRPnNlwvD6eeA6cu5d7UlrikrcbTEf7S+16QmpS1zr1SB65BQs147lro/jtS4ZM8u3+Nc3fAE1VRMqVetP/xI7wTGtLqhzQ6aymD1f0LkygnOCOj5TKYTnNNnxtE3+LWG6XIHfGX1yVv1jLca28bhistIWXXoTlCHpxzW7cOWOElxToONO4Rnr5c6uZaeLXSRKYAQBOviNWCs193kLfinWOimmOwD087kunqzKipeujUoM9+wU0zr6qis2R6xcqOWDAgzrEJIkzXNyd3IGFwJNwnezdXIcG1wmn7f3/MPAbx/SaaubwaqOv75bDCa+Wu9tOooDEWEnF3wKd+O0T1aGoOollzWra8s5K9Eysj3gDsd0UweSA/+GDAcJjeWVd5zcpt5+hub74AmvnSp3/3vdL4J8+fqwy94mdPnns="
branches: 
only:
- master
