sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: m0RKof28jO7NGwEB46pf1XbJoCTqfVJ1uvCLhNVFtSM8CHd4nvIz6qJWHJhZxmd1Rv5a/PDoEaB96iJ1YVwCuxImQmrbITppC8vAWJY+ysoZwkzIj/8e3krwJSqjyBn1fFVnQ6IYAc/Z0b8kUnZxjLpkz3tLTylT0GbgCnVMPgyzS6mJ1lsXKzmkv1wdmKU4+s0+74vQCPrf9Uq/tiKau0NC7hjZK/34VxUdjg/9Wmz+1zV1IMUwnJI/RkIk6fCPUzRcGGnPnaqbKw3V5dmMnbzvwf5N+KreKpMplgqHVCMalNUDG0FgQmiz7dgeKgIiPgPTvKuLcyMsZdkChfZkpqjiYKQehgkTicnDqPfGPV3/uejl1fZCYpgDlrRX9KvMCOoGU1yuQIPSzVUtiZ2zUBX8O3/MiPtiPd8a08nRSMdYHOeJs4WxJDM3YdOQaY9XkNjq4zVoX6GnFkpzWBEc/qXbDlA9F3sxZ07U5xYgeRaf6nrCIawRA3N1dQOka4aFheb5F3PKvS8k4vky2pNvnbj9Tps6vCV0wnPe/nwmwIxK8tO2MoMJ4eDYMwVN2WAzOf986C26kLkQ2u9v2pFAvqfQ94mFDwWu9ADMNon1UtedILnZPDMS1aTsNnO0LBUkKVCfY85U/qIjQUXHpG8U9J9VBbuDAkYAVvgqyOe+Lhg=
    #branches: 
    #only:
    #- master
