sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: YJmTVqKc3fCvjDOYe20z0dsP94K1gCQMPNi1oqzqxM3daGVNR6a0FK1GgZDdA7KnJFBy7AVDoGyNRMspmJnsJ3C2BVyVfxnQRz4JsGRwxeh/01Z7mBt7RKrLmmjDIFquBHPPI+eslHObJ7lFsEFYCLxcniHN20K3WBMFHrHvIxv5EB4trNRNhbNJ3j2WLQTVLp869jK0+j0w6XTKi7JX1Aru9H6SvnZPeV3C/eE1hTjcRfkroRJ4ypJZbgHU/bM4qaCy9WUYYW1XfzIZTvdgTaCNCvsZjMudcsUWZ6yQ30o4bZSpVgzjA9wzAvqevRFj7ziVuCl10pCLZqd9u9UWOhGbDUlk4ZnIQnkGK2BnIok2ajiZElK4DfffXU2SHPCbP8xGwEd/nmXpLktXET2SZ8/XZxNrfUc/yBW1l6m45cuuHHGwDdFqcRfd8aYAQTJNEApyFwT31jOnNfKM//hHxsprT27g6vGcAZrBV7d2OeFAt4pAHERg7871m8VP/QI5rwC/grNXkpUlGKQzQxLVZtPoo/PlagirlN5EnCoH31NOvqoOleVQ5HzbCfJVLZlYCaFxgU6B9KRZHrHD9YrZmF0bBppaXja6al3jxin6AX1DYVx+ZE4PBHQQl/lvA2mrpXx1pLRkAuACHy1QGEDvL62sMqFNgHHGGnEq4Yv12a4=
branches: 
only:
- master
