# Jykell configuration
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
paginate: 5
language: 'es-es'

# Website info
name: 'Aula Taller'
description: "Un blog para las clases, para dejar registro y para probar actividades"

# Author's info
author: 'Alvar Maciel'
# edit 'categories' in the front matter of every post to match this username
username: alvarmaciel
bio: 'Docente, busco entender que hacer con el engranaje tecnologico en el que estamos metidxs. Trabajo y escribo acerca de la educación.'
location: 'Buenos Aires, Argentina'
url: 'http://acercadelaeducacion.github.io/aulataller'
image: 'assets/images/alvar.png'

short_url: 'aulataller'
google_analytics: 
disqus: aulataller
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /aulataller/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
#safe: false
#lsi: false
#username: alvarmaciel
#repo: aulataller
#branch: gh-pages
#relative_source: ../aulataller/
#destination: ../_sites/
#production_url:  https://acercadelaeducacion.github.io/aulataller/
#source_url:      https://github.com/acercadelaeducacion/aulataller/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
